#!/usr/bin/with-contenv bash

pip3 install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip3 install -U 'setuptools>=36'
pip3 install -U 'urllib3[socks]'
pip3 install -U 'chardet'
pip3 install -U 'irc_bot'
pip3 install -U 'rarfile'


# Install flexget last (it might force specific versions of other packages).
pip3 install -U flexget
